<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>lfe</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>LFE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.parens.lfe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[()]</string>
			<key>name</key>
			<string>source.parens.lfe</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lfe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.lfe</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.lfe</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lfe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\b(?i:(def[a-z\-]*|include-file|include-lib|set))\b)(\s+)((\w|\.|\\|&lt;|\-|\!|\?|&gt;)*)</string>
			<key>name</key>
			<string>meta.function.lfe</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.lfe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(\w|[\\+-=&lt;&gt;'"&amp;#])+</string>
			<key>name</key>
			<string>constant.character.lfe</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.lfe</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.lfe</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\*)(\S*)(\*)</string>
			<key>name</key>
			<string>variable.other.global.lfe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![*+!_?\-])\b(case|do|let|loop|if|else|when|receive|!|\?)\b(?![*+!_?\-])</string>
			<key>name</key>
			<string>keyword.control.lfe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![*+!_?\-])\b(eq|neq|and|or|==|=:=|&lt;=|&gt;|&lt;|&lt;&gt;|=/=|/=)(?!-)\b(?![*+!_?\-])</string>
			<key>name</key>
			<string>keyword.operator.lfe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?&lt;!-)(?i:ok|undefined|null|nil)(?!-)\b</string>
			<key>name</key>
			<string>constant.language.lfe</string>
		</dict>
		<dict>
			<key>match</key>
            <string>(?&lt;![*+!_?\-\.&gt;&lt;])\b(cons|car|cdr|cond|lambda|\\|\.\\|-&gt;|-&gt;&gt;|&lt;-|&lt;=|\?=|\w+:\w+|acons|pairlis|assoc|assoc-if|assoc-if-not|rassoc|rassoc-if|rassoc-if-not|subst|subst-if|subst-if-not|sublis|quote|unquote|backquote|eval|append|list||t|load|progn|prog1|prog2|tuple|list|binary|match-\w+|let-rec|let-marco|receive|catch|try|error|funcall|call|list*|let*|flet*|flet|fletrec|andalso|orelse|fun|lc|list-comp|bc|binary-comp|match-spec|defsyntax|macrolet|syntaxlet|map|map-get|map-set|map-update|export|import|from|rename)\b(?![*+!_?\-\.&gt;&lt;])</string>
			<key>name</key>
			<string>support.function.lfe</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|true|false|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.lfe</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lfe</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lfe</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lfe</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lfe</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lfe</string>
	<key>uuid</key>
	<string>0fb78eb3-f609-46b1-a030-f7176ffb08a6</string>
</dict>
</plist>
